### PR TITLE
LPS-114054 Update test and snapshot

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
ci:test:app-builder

**Comment by alexcandidos** [comment]
Hey @alinedoleron @brunofarache , the errors found on App Builder suite are known issues as you can see here https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1177367983. ;)

**Comment by alinedoleron** [comment]
Thank you very much, @alexcandidos !!!

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
