### PR TITLE
LPS-108987 Restore previous sidebar css class and remove no longer needed css properties

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
ci:forward

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
ci:forward

**Comment by brunofarache** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
ci:stop

**Comment by brunofarache** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
ci:test:relevant

**Pull request closed without merging**
