### PR TITLE
LPS-101162 Adapt post method to enable save App with no Data Layout and Data List View

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78136. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/0f83c3cba570~1...0f83c3cba570)

**Pull request closed without merging**
