### PR TITLE
LPS-111775 Include dropdown items for kebab

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by brunofarache** [comment]
@carolmariaabb @cvanut

several poshi tests failing for `ci:test:forms`. Please either quarantine or fix them, I won't merge anything until `ci:test:forms` is green again.

I made a mistake that was fixed by Carol at https://github.com/brunofarache/liferay-portal/pull/170/commits/c61dbab0d3a95aa5fc90052b3cc90d016fc92d7a

Going to send to Brian this fix only.

**Comment by brunofarache** [comment]
Sent fix to https://github.com/brunofarache/liferay-portal/pull/171

This will fix about 10 poshi tests, there are other remaining 10 that are constantly failing, those are the ones that should be fixed or quarantine.

cc @cvanut @natocesarrego

**Comment by brunofarache** [comment]
ci:test:forms

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/172.

**Comment by brunofarache** [comment]
ci:stop

**Pull request closed without merging**
