### PR TITLE
LPS-105449 Implement the permissions endpoints

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82177. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/b9b4db3edfc4~6...b9b4db3edfc4)

**Pull request closed without merging**
