### PR TITLE
LPS-113209 Show editingLanguageId label on the CustomObjectFieldsList

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/281. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/2bb2db7e5634~1...2bb2db7e5634)

**Pull request closed without merging**
