### PR TITLE
LPS-113143 Add new language keys

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/270. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/08fddc89596e~10...08fddc89596e)

**Pull request closed without merging**
