### PR TITLE
LPS-100953 Retrieve the ids with GetterUtil

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78670. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/e0068fb8eacf~1...e0068fb8eacf)

**Pull request closed without merging**
