### PR TITLE
LPS-106231 Remove unecessary endpoints

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:app-builder

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/651. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/3833b52753d6~4...3833b52753d6)

**Pull request closed without merging**
