### PR TITLE
LPS-112039 Add tests to TableView (ListTableViews)

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/190. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/e84585bc79e8~4...e84585bc79e8)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/191. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/e84585bc79e8~4...e84585bc79e8)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/196. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/07f4950abcef~4...07f4950abcef)

**Pull request closed without merging**
