### PR TITLE
LPS-112751

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/88363

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/244. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/6afa59b7e057~1...6afa59b7e057)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/250. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/ad160b20b115~2...ad160b20b115)

**Pull request closed without merging**
