### PR TITLE
LPS-99296 Throw IllegalStateException

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/77935.

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78324. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/bed5b366233e~1...bed5b366233e)

**Pull request closed without merging**
