### PR TITLE
LPS-111681 | LPS-112655 Regen

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:app-builder

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/232. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/25124e7e409b~6...25124e7e409b)

**Pull request closed without merging**
