### PR TITLE
LPS-102348 Create DDMStructure Model Listener in App Builder bundle

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant

Restarting test, failure might have been an unrelated server issue.
`Target exception: java.lang.RuntimeException: Unable to get branches with SHA 149be4a64d3e0ff4d5e723d471d5ce27789200ce`

**Comment by brunofarache** [comment]
Just started reviewing :)

**Pull request closed without merging**
