### PR TITLE
LPS-99567 Call get DEDataListViews when the keywords field is empty

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77052. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/cbaca8fdf5a9~1...cbaca8fdf5a9)

**Pull request closed without merging**
