### PR TITLE
LPS-99296 Add Layout Type Controller

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/gabrielwas/liferay-portal/pull/86. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/06d0f477fa91~1...06d0f477fa91)

**Pull request closed without merging**
