### PR TITLE
LPS-114159 Add method to adjust decimal to floor

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/312. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/be64a3c8820e~1...be64a3c8820e)

**Pull request closed without merging**
