### PR TITLE
LPS-104958 buildLang

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81523. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/deab38b24905~5...deab38b24905)

**Pull request closed without merging**
