### PR TITLE
LPS-113718 Organize dropdown items

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/334. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/9d3f84fb7cc6~1...9d3f84fb7cc6)

**Pull request closed without merging**
