### PR TITLE
LPS-109656

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/88102

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/221. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/427ad1cd46b4~2...427ad1cd46b4)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/222. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/9ef4270603e6~3...9ef4270603e6)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/224. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/476b3e704480~3...476b3e704480)

**Pull request closed without merging**
