### PR TITLE
LPS-112926 Fix app builder snapshot test

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
ci:forward

**Comment by vicnate5** [comment]
@brunofarache any idea how the failure this fixes got through relevant testing? We always run all the js-unit tests in relevant

**Comment by jpince** [comment]
@vicnate5 @brunofarache can we send this straight to BChan to unblock PRs?

I see some failures in the [jenkins log](https://test-1-14.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5995/jenkins-report.html), not sure if they're related.

**Comment by vicnate5** [comment]
Checking the failures

**Comment by vicnate5** [comment]
Pushed manually: https://github.com/brianchandotcom/liferay-portal/pull/88567

**Comment by vicnate5** [comment]
I closed the forward. There is a possible regression here. App Builder didn't load on the poshi test.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@alexcandidos

**Comment by alexcandidos** [comment]
Hey @vicnate5 , the failed execution of AppBuilder#DeleteFormViewFieldFromObject seems to be flaky of CI. The step that is failing (AppBuilderAdmin#addCustomObject) is present in ALL the executions of App Builder scripts, as we can see here, a lot of other jobs/app-builder scripts are passing in this PR, so I believe we can ignore this failure.

BTW: It is also weird why Github is saying that this failure is in common with acceptance upstream since it is [consistently passing on CI in another test routine](https://testray.liferay.com/home/-/testray/case_results/1154719641/history?tab=result&hideFilterPin=true).

Best Regards

**Pull request closed without merging**
