### PR TITLE
LPS-112751 Pass report data to react app

### PR DESCRIPTION
**Pull request by marcosapmf**

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:forward

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/240. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/8426bc5d04a4~7...8426bc5d04a4)

**Pull request closed without merging**
