### PR TITLE
LPS-108987 Fix sidebar within table view page

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
ci:forward

**Comment by brunofarache** [comment]
ci:stop

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/153. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/9e79f5b986f5~1...9e79f5b986f5)

**Comment by brunofarache** [comment]
@interaminense source formatter error.

**Comment by interaminense** [comment]
Just started reviewing :)

**Pull request closed without merging**
