### PR TITLE
LPS-111789 SF

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
ci:forward

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Sent new Pr to https://github.com/brunofarache/liferay-portal/pull/314

**Pull request closed without merging**
