### PR TITLE
LPS-101545 baseline

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78548. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/1e7226696539~2...1e7226696539)

**Pull request closed without merging**
