### PR TITLE
LPS-113758 Add button to create Data Provider from the empty state message

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
ci:forward

**Comment by brunofarache** [comment]
ci:forward

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/298.

**Pull request closed without merging**
