### PR TITLE
LPS-106424 Fix path and action id

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:app-builder

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/665. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/581f217807b6~8...581f217807b6)

**Pull request closed without merging**
