### PR TITLE
LPS-111775 Implement Header

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/182. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/7e5c4b6a2675~8...7e5c4b6a2675)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/183. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/84418658d4fb~8...84418658d4fb)

**Pull request closed without merging**
