### PR TITLE
LPS-111789 Update languages

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:forward

**Comment by brunofarache** [comment]
Just started reviewing :)

**Comment by brunofarache** [comment]
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/317. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/f2a0647544b9~1...f2a0647544b9)

**Pull request closed without merging**
